services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    secrets:
      - llm_api_key
      - els_api_key
      - els_token
    volumes:
      - ./api:/app

  ui:
    build:
      context: ./ui
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5001
      - WATCHPACK_POLLING=true 
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api
