services:
  api:
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - LLM_API_KEY=${LLM_API_KEY:-default_value}
      - ELS_API_KEY=${ELS_API_KEY:-default_value}
      - ELS_TOKEN=${ELS_TOKEN:-default_value}
    secrets:
      - llm_api_key
      - els_api_key
      - els_token
    volumes:
      - ./api:/app

  ui:
    build:
      context: ./ui
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api

secrets:
  llm_api_key:
    file: ./secrets/llm_api_key.txt
  els_api_key:
    file: ./secrets/els_api_key.txt
  els_token:
    file: ./secrets/els_token.txt
