version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: test.Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=test
    secrets:
      - llm_api_key
      - els_api_key
      - els_token
    volumes:
      - ./api:/app
    command: pytest  # Run API tests automatically

  ui:
    build:
      context: ./ui
      dockerfile: test.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - NEXT_PUBLIC_API_URL=http://localhost:5001  # API URL for tests
    volumes:
      - ./ui:/app
      - /app/node_modules
    depends_on:
      - api
    command: npm run test  # Run UI tests automatically

secrets:
  llm_api_key:
    file: ./secrets/llm_api_key.txt
  els_api_key:
    file: ./secrets/els_api_key.txt
  els_token:
    file: ./secrets/els_token.txt
